/*
   ChargeTime.eu - Java-OCA-OCPP

   MIT License

   Permission is hereby granted, free of charge, to any person obtaining a copy
   of this software and associated documentation files (the "Software"), to deal
   in the Software without restriction, including without limitation the rights
   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
   copies of the Software, and to permit persons to whom the Software is
   furnished to do so, subject to the following conditions:

   The above copyright notice and this permission notice shall be included in all
   copies or substantial portions of the Software.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
   SOFTWARE.
*/

package eu.chargetime.ocpp.v21.model.messages;

import eu.chargetime.ocpp.PropertyConstraintException;
import eu.chargetime.ocpp.model.RequestWithId;
import eu.chargetime.ocpp.utilities.MoreObjects;
import eu.chargetime.ocpp.v21.model.types.Address;
import eu.chargetime.ocpp.v21.model.types.CustomData;
import eu.chargetime.ocpp.v21.model.types.PaymentStatusEnum;
import java.time.ZonedDateTime;
import java.util.Objects;
import javax.annotation.Nullable;

/**
 * NotifySettlementRequest
 *
 * <p>OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International
 * Public License
 */
public final class NotifySettlementRequest extends RequestWithId {
  /**
   * The transactionId that the settlement belongs to. Can be empty if the payment transaction is
   * canceled prior to the start of the OCPP transaction.
   */
  @Nullable private String transactionId;

  /**
   * The payment reference received from the payment terminal and is used as the value for idToken.
   */
  private String pspRef;

  /** The status of the settlement attempt. */
  private PaymentStatusEnum status;

  /** Additional information from payment terminal/payment process. */
  @Nullable private String statusInfo;

  /** The amount that was settled, or attempted to be settled (in case of failure). */
  private Double settlementAmount;

  /** The time when the settlement was done. */
  private ZonedDateTime settlementTime;

  /** receiptId */
  @Nullable private String receiptId;

  /** The receipt URL, to be used if the receipt is generated by the payment terminal or the CS. */
  @Nullable private String receiptUrl;

  /** A generic address format. */
  @Nullable private Address vatCompany;

  /** VAT number for a company receipt. */
  @Nullable private String vatNumber;

  /** Custom data */
  @Nullable private CustomData customData;

  /**
   * Constructor for the NotifySettlementRequest class
   *
   * @param pspRef The payment reference received from the payment terminal and is used as the value
   *     for idToken.
   * @param status The status of the settlement attempt.
   * @param settlementAmount The amount that was settled, or attempted to be settled (in case of
   *     failure).
   * @param settlementTime The time when the settlement was done.
   */
  public NotifySettlementRequest(
      String pspRef,
      PaymentStatusEnum status,
      Double settlementAmount,
      ZonedDateTime settlementTime) {
    setPspRef(pspRef);
    setStatus(status);
    setSettlementAmount(settlementAmount);
    setSettlementTime(settlementTime);
  }

  /**
   * Gets the transactionId that the settlement belongs to. Can be empty if the payment transaction
   * is canceled prior to the start of the OCPP transaction.
   *
   * @return The transactionId that the settlement belongs to
   */
  @Nullable
  public String getTransactionId() {
    return transactionId;
  }

  /**
   * Sets the transactionId that the settlement belongs to. Can be empty if the payment transaction
   * is canceled prior to the start of the OCPP transaction.
   *
   * @param transactionId The transactionId that the settlement belongs to
   */
  public void setTransactionId(@Nullable String transactionId) {
    if (!isValidTransactionId(transactionId)) {
      throw new PropertyConstraintException(transactionId, "transactionId is invalid");
    }
    this.transactionId = transactionId;
  }

  /**
   * Returns whether the given transactionId is valid
   *
   * @param transactionId the transactionId to check the validity of
   * @return {@code true} if transactionId is valid, {@code false} if not
   */
  private boolean isValidTransactionId(@Nullable String transactionId) {
    return transactionId == null || transactionId.length() <= 36;
  }

  /**
   * Adds the transactionId that the settlement belongs to. Can be empty if the payment transaction
   * is canceled prior to the start of the OCPP transaction.
   *
   * @param transactionId The transactionId that the settlement belongs to
   * @return this
   */
  public NotifySettlementRequest withTransactionId(@Nullable String transactionId) {
    setTransactionId(transactionId);
    return this;
  }

  /**
   * Gets the payment reference received from the payment terminal and is used as the value for
   * idToken.
   *
   * @return The payment reference received from the payment terminal and is used as the value for
   *     idToken
   */
  public String getPspRef() {
    return pspRef;
  }

  /**
   * Sets the payment reference received from the payment terminal and is used as the value for
   * idToken.
   *
   * @param pspRef The payment reference received from the payment terminal and is used as the value
   *     for idToken
   */
  public void setPspRef(String pspRef) {
    if (!isValidPspRef(pspRef)) {
      throw new PropertyConstraintException(pspRef, "pspRef is invalid");
    }
    this.pspRef = pspRef;
  }

  /**
   * Returns whether the given pspRef is valid
   *
   * @param pspRef the pspRef to check the validity of
   * @return {@code true} if pspRef is valid, {@code false} if not
   */
  private boolean isValidPspRef(String pspRef) {
    return pspRef != null && pspRef.length() <= 255;
  }

  /**
   * Gets the status of the settlement attempt.
   *
   * @return The status of the settlement attempt
   */
  public PaymentStatusEnum getStatus() {
    return status;
  }

  /**
   * Sets the status of the settlement attempt.
   *
   * @param status The status of the settlement attempt
   */
  public void setStatus(PaymentStatusEnum status) {
    if (!isValidStatus(status)) {
      throw new PropertyConstraintException(status, "status is invalid");
    }
    this.status = status;
  }

  /**
   * Returns whether the given status is valid
   *
   * @param status the status to check the validity of
   * @return {@code true} if status is valid, {@code false} if not
   */
  private boolean isValidStatus(PaymentStatusEnum status) {
    return status != null;
  }

  /**
   * Gets additional information from payment terminal/payment process.
   *
   * @return Additional information from payment terminal/payment process
   */
  @Nullable
  public String getStatusInfo() {
    return statusInfo;
  }

  /**
   * Sets additional information from payment terminal/payment process.
   *
   * @param statusInfo Additional information from payment terminal/payment process
   */
  public void setStatusInfo(@Nullable String statusInfo) {
    if (!isValidStatusInfo(statusInfo)) {
      throw new PropertyConstraintException(statusInfo, "statusInfo is invalid");
    }
    this.statusInfo = statusInfo;
  }

  /**
   * Returns whether the given statusInfo is valid
   *
   * @param statusInfo the statusInfo to check the validity of
   * @return {@code true} if statusInfo is valid, {@code false} if not
   */
  private boolean isValidStatusInfo(@Nullable String statusInfo) {
    return statusInfo == null || statusInfo.length() <= 500;
  }

  /**
   * Adds additional information from payment terminal/payment process.
   *
   * @param statusInfo Additional information from payment terminal/payment process
   * @return this
   */
  public NotifySettlementRequest withStatusInfo(@Nullable String statusInfo) {
    setStatusInfo(statusInfo);
    return this;
  }

  /**
   * Gets the amount that was settled, or attempted to be settled (in case of failure).
   *
   * @return The amount that was settled, or attempted to be settled (in case of failure)
   */
  public Double getSettlementAmount() {
    return settlementAmount;
  }

  /**
   * Sets the amount that was settled, or attempted to be settled (in case of failure).
   *
   * @param settlementAmount The amount that was settled, or attempted to be settled (in case of
   *     failure)
   */
  public void setSettlementAmount(Double settlementAmount) {
    if (!isValidSettlementAmount(settlementAmount)) {
      throw new PropertyConstraintException(settlementAmount, "settlementAmount is invalid");
    }
    this.settlementAmount = settlementAmount;
  }

  /**
   * Returns whether the given settlementAmount is valid
   *
   * @param settlementAmount the settlementAmount to check the validity of
   * @return {@code true} if settlementAmount is valid, {@code false} if not
   */
  private boolean isValidSettlementAmount(Double settlementAmount) {
    return settlementAmount != null;
  }

  /**
   * Gets the time when the settlement was done.
   *
   * @return The time when the settlement was done
   */
  public ZonedDateTime getSettlementTime() {
    return settlementTime;
  }

  /**
   * Sets the time when the settlement was done.
   *
   * @param settlementTime The time when the settlement was done
   */
  public void setSettlementTime(ZonedDateTime settlementTime) {
    if (!isValidSettlementTime(settlementTime)) {
      throw new PropertyConstraintException(settlementTime, "settlementTime is invalid");
    }
    this.settlementTime = settlementTime;
  }

  /**
   * Returns whether the given settlementTime is valid
   *
   * @param settlementTime the settlementTime to check the validity of
   * @return {@code true} if settlementTime is valid, {@code false} if not
   */
  private boolean isValidSettlementTime(ZonedDateTime settlementTime) {
    return settlementTime != null;
  }

  /**
   * Gets receiptId
   *
   * @return receiptId
   */
  @Nullable
  public String getReceiptId() {
    return receiptId;
  }

  /**
   * Sets receiptId
   *
   * @param receiptId receiptId
   */
  public void setReceiptId(@Nullable String receiptId) {
    if (!isValidReceiptId(receiptId)) {
      throw new PropertyConstraintException(receiptId, "receiptId is invalid");
    }
    this.receiptId = receiptId;
  }

  /**
   * Returns whether the given receiptId is valid
   *
   * @param receiptId the receiptId to check the validity of
   * @return {@code true} if receiptId is valid, {@code false} if not
   */
  private boolean isValidReceiptId(@Nullable String receiptId) {
    return receiptId == null || receiptId.length() <= 50;
  }

  /**
   * Adds receiptId
   *
   * @param receiptId receiptId
   * @return this
   */
  public NotifySettlementRequest withReceiptId(@Nullable String receiptId) {
    setReceiptId(receiptId);
    return this;
  }

  /**
   * Gets the receipt URL, to be used if the receipt is generated by the payment terminal or the CS.
   *
   * @return The receipt URL, to be used if the receipt is generated by the payment terminal or the
   *     CS
   */
  @Nullable
  public String getReceiptUrl() {
    return receiptUrl;
  }

  /**
   * Sets the receipt URL, to be used if the receipt is generated by the payment terminal or the CS.
   *
   * @param receiptUrl The receipt URL, to be used if the receipt is generated by the payment
   *     terminal or the CS
   */
  public void setReceiptUrl(@Nullable String receiptUrl) {
    if (!isValidReceiptUrl(receiptUrl)) {
      throw new PropertyConstraintException(receiptUrl, "receiptUrl is invalid");
    }
    this.receiptUrl = receiptUrl;
  }

  /**
   * Returns whether the given receiptUrl is valid
   *
   * @param receiptUrl the receiptUrl to check the validity of
   * @return {@code true} if receiptUrl is valid, {@code false} if not
   */
  private boolean isValidReceiptUrl(@Nullable String receiptUrl) {
    return receiptUrl == null || receiptUrl.length() <= 2000;
  }

  /**
   * Adds the receipt URL, to be used if the receipt is generated by the payment terminal or the CS.
   *
   * @param receiptUrl The receipt URL, to be used if the receipt is generated by the payment
   *     terminal or the CS
   * @return this
   */
  public NotifySettlementRequest withReceiptUrl(@Nullable String receiptUrl) {
    setReceiptUrl(receiptUrl);
    return this;
  }

  /**
   * Gets a generic address format.
   *
   * @return A generic address format
   */
  @Nullable
  public Address getVatCompany() {
    return vatCompany;
  }

  /**
   * Sets a generic address format.
   *
   * @param vatCompany A generic address format
   */
  public void setVatCompany(@Nullable Address vatCompany) {
    if (!isValidVatCompany(vatCompany)) {
      throw new PropertyConstraintException(vatCompany, "vatCompany is invalid");
    }
    this.vatCompany = vatCompany;
  }

  /**
   * Returns whether the given vatCompany is valid
   *
   * @param vatCompany the vatCompany to check the validity of
   * @return {@code true} if vatCompany is valid, {@code false} if not
   */
  private boolean isValidVatCompany(@Nullable Address vatCompany) {
    return vatCompany == null || vatCompany.validate();
  }

  /**
   * Adds a generic address format.
   *
   * @param vatCompany A generic address format
   * @return this
   */
  public NotifySettlementRequest withVatCompany(@Nullable Address vatCompany) {
    setVatCompany(vatCompany);
    return this;
  }

  /**
   * Gets VAT number for a company receipt.
   *
   * @return VAT number for a company receipt
   */
  @Nullable
  public String getVatNumber() {
    return vatNumber;
  }

  /**
   * Sets VAT number for a company receipt.
   *
   * @param vatNumber VAT number for a company receipt
   */
  public void setVatNumber(@Nullable String vatNumber) {
    if (!isValidVatNumber(vatNumber)) {
      throw new PropertyConstraintException(vatNumber, "vatNumber is invalid");
    }
    this.vatNumber = vatNumber;
  }

  /**
   * Returns whether the given vatNumber is valid
   *
   * @param vatNumber the vatNumber to check the validity of
   * @return {@code true} if vatNumber is valid, {@code false} if not
   */
  private boolean isValidVatNumber(@Nullable String vatNumber) {
    return vatNumber == null || vatNumber.length() <= 20;
  }

  /**
   * Adds VAT number for a company receipt.
   *
   * @param vatNumber VAT number for a company receipt
   * @return this
   */
  public NotifySettlementRequest withVatNumber(@Nullable String vatNumber) {
    setVatNumber(vatNumber);
    return this;
  }

  /**
   * Gets custom data
   *
   * @return Custom data
   */
  @Nullable
  public CustomData getCustomData() {
    return customData;
  }

  /**
   * Sets custom data
   *
   * @param customData Custom data
   */
  public void setCustomData(@Nullable CustomData customData) {
    if (!isValidCustomData(customData)) {
      throw new PropertyConstraintException(customData, "customData is invalid");
    }
    this.customData = customData;
  }

  /**
   * Returns whether the given customData is valid
   *
   * @param customData the customData to check the validity of
   * @return {@code true} if customData is valid, {@code false} if not
   */
  private boolean isValidCustomData(@Nullable CustomData customData) {
    return customData == null || customData.validate();
  }

  /**
   * Adds custom data
   *
   * @param customData Custom data
   * @return this
   */
  public NotifySettlementRequest withCustomData(@Nullable CustomData customData) {
    setCustomData(customData);
    return this;
  }

  @Override
  public boolean validate() {
    return isValidTransactionId(transactionId)
        && isValidPspRef(pspRef)
        && isValidStatus(status)
        && isValidStatusInfo(statusInfo)
        && isValidSettlementAmount(settlementAmount)
        && isValidSettlementTime(settlementTime)
        && isValidReceiptId(receiptId)
        && isValidReceiptUrl(receiptUrl)
        && isValidVatCompany(vatCompany)
        && isValidVatNumber(vatNumber)
        && isValidCustomData(customData);
  }

  @Override
  public boolean transactionRelated() {
    return false;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NotifySettlementRequest that = (NotifySettlementRequest) o;
    return Objects.equals(transactionId, that.transactionId)
        && Objects.equals(pspRef, that.pspRef)
        && Objects.equals(status, that.status)
        && Objects.equals(statusInfo, that.statusInfo)
        && Objects.equals(settlementAmount, that.settlementAmount)
        && Objects.equals(settlementTime, that.settlementTime)
        && Objects.equals(receiptId, that.receiptId)
        && Objects.equals(receiptUrl, that.receiptUrl)
        && Objects.equals(vatCompany, that.vatCompany)
        && Objects.equals(vatNumber, that.vatNumber)
        && Objects.equals(customData, that.customData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        transactionId,
        pspRef,
        status,
        statusInfo,
        settlementAmount,
        settlementTime,
        receiptId,
        receiptUrl,
        vatCompany,
        vatNumber,
        customData);
  }

  @Override
  public String toString() {
    return MoreObjects.toStringHelper(this)
        .add("transactionId", transactionId)
        .add("pspRef", pspRef)
        .add("status", status)
        .add("statusInfo", statusInfo)
        .add("settlementAmount", settlementAmount)
        .add("settlementTime", settlementTime)
        .add("receiptId", receiptId)
        .add("receiptUrl", receiptUrl)
        .add("vatCompany", vatCompany)
        .add("vatNumber", vatNumber)
        .add("customData", customData)
        .add("isValid", validate())
        .toString();
  }
}
