/*
   ChargeTime.eu - Java-OCA-OCPP

   MIT License

   Permission is hereby granted, free of charge, to any person obtaining a copy
   of this software and associated documentation files (the "Software"), to deal
   in the Software without restriction, including without limitation the rights
   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
   copies of the Software, and to permit persons to whom the Software is
   furnished to do so, subject to the following conditions:

   The above copyright notice and this permission notice shall be included in all
   copies or substantial portions of the Software.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
   SOFTWARE.
*/

package eu.chargetime.ocpp.v21.model.messages;

import eu.chargetime.ocpp.PropertyConstraintException;
import eu.chargetime.ocpp.model.Confirmation;
import eu.chargetime.ocpp.utilities.MoreObjects;
import eu.chargetime.ocpp.v21.model.types.CustomData;
import java.util.Objects;
import javax.annotation.Nullable;

/**
 * NotifySettlementResponse
 *
 * <p>OCPP 2.1 Edition 1 (c) OCA, Creative Commons Attribution-NoDerivatives 4.0 International
 * Public License
 */
public final class NotifySettlementResponse extends Confirmation {
  /**
   * The receipt URL if receipt generated by CSMS. The Charging Station can QR encode it and show it
   * to the EV Driver.
   */
  @Nullable private String receiptUrl;

  /** The receipt id if the receipt is generated by CSMS. */
  @Nullable private String receiptId;

  /** Custom data */
  @Nullable private CustomData customData;

  /** Constructor for the NotifySettlementResponse class */
  public NotifySettlementResponse() {}

  /**
   * Gets the receipt URL if receipt generated by CSMS. The Charging Station can QR encode it and
   * show it to the EV Driver.
   *
   * @return The receipt URL if receipt generated by CSMS
   */
  @Nullable
  public String getReceiptUrl() {
    return receiptUrl;
  }

  /**
   * Sets the receipt URL if receipt generated by CSMS. The Charging Station can QR encode it and
   * show it to the EV Driver.
   *
   * @param receiptUrl The receipt URL if receipt generated by CSMS
   */
  public void setReceiptUrl(@Nullable String receiptUrl) {
    if (!isValidReceiptUrl(receiptUrl)) {
      throw new PropertyConstraintException(receiptUrl, "receiptUrl is invalid");
    }
    this.receiptUrl = receiptUrl;
  }

  /**
   * Returns whether the given receiptUrl is valid
   *
   * @param receiptUrl the receiptUrl to check the validity of
   * @return {@code true} if receiptUrl is valid, {@code false} if not
   */
  private boolean isValidReceiptUrl(@Nullable String receiptUrl) {
    return receiptUrl == null || receiptUrl.length() <= 2000;
  }

  /**
   * Adds the receipt URL if receipt generated by CSMS. The Charging Station can QR encode it and
   * show it to the EV Driver.
   *
   * @param receiptUrl The receipt URL if receipt generated by CSMS
   * @return this
   */
  public NotifySettlementResponse withReceiptUrl(@Nullable String receiptUrl) {
    setReceiptUrl(receiptUrl);
    return this;
  }

  /**
   * Gets the receipt id if the receipt is generated by CSMS.
   *
   * @return The receipt id if the receipt is generated by CSMS
   */
  @Nullable
  public String getReceiptId() {
    return receiptId;
  }

  /**
   * Sets the receipt id if the receipt is generated by CSMS.
   *
   * @param receiptId The receipt id if the receipt is generated by CSMS
   */
  public void setReceiptId(@Nullable String receiptId) {
    if (!isValidReceiptId(receiptId)) {
      throw new PropertyConstraintException(receiptId, "receiptId is invalid");
    }
    this.receiptId = receiptId;
  }

  /**
   * Returns whether the given receiptId is valid
   *
   * @param receiptId the receiptId to check the validity of
   * @return {@code true} if receiptId is valid, {@code false} if not
   */
  private boolean isValidReceiptId(@Nullable String receiptId) {
    return receiptId == null || receiptId.length() <= 50;
  }

  /**
   * Adds the receipt id if the receipt is generated by CSMS.
   *
   * @param receiptId The receipt id if the receipt is generated by CSMS
   * @return this
   */
  public NotifySettlementResponse withReceiptId(@Nullable String receiptId) {
    setReceiptId(receiptId);
    return this;
  }

  /**
   * Gets custom data
   *
   * @return Custom data
   */
  @Nullable
  public CustomData getCustomData() {
    return customData;
  }

  /**
   * Sets custom data
   *
   * @param customData Custom data
   */
  public void setCustomData(@Nullable CustomData customData) {
    if (!isValidCustomData(customData)) {
      throw new PropertyConstraintException(customData, "customData is invalid");
    }
    this.customData = customData;
  }

  /**
   * Returns whether the given customData is valid
   *
   * @param customData the customData to check the validity of
   * @return {@code true} if customData is valid, {@code false} if not
   */
  private boolean isValidCustomData(@Nullable CustomData customData) {
    return customData == null || customData.validate();
  }

  /**
   * Adds custom data
   *
   * @param customData Custom data
   * @return this
   */
  public NotifySettlementResponse withCustomData(@Nullable CustomData customData) {
    setCustomData(customData);
    return this;
  }

  @Override
  public boolean validate() {
    return isValidReceiptUrl(receiptUrl)
        && isValidReceiptId(receiptId)
        && isValidCustomData(customData);
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NotifySettlementResponse that = (NotifySettlementResponse) o;
    return Objects.equals(receiptUrl, that.receiptUrl)
        && Objects.equals(receiptId, that.receiptId)
        && Objects.equals(customData, that.customData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(receiptUrl, receiptId, customData);
  }

  @Override
  public String toString() {
    return MoreObjects.toStringHelper(this)
        .add("receiptUrl", receiptUrl)
        .add("receiptId", receiptId)
        .add("customData", customData)
        .add("isValid", validate())
        .toString();
  }
}
